# 어플리케이션 포트 => 디폴트가 8080
server:
  port: 8088

# ai api 설정
ai:
  base-url: http://52.78.177.7:5000/predict  # AWS Lightsail - AI API URL

# DB 설정
# mybatis
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
#  type-aliases-package: com.example.demo.dtd 